### ISSUE TITLE
Random API Limits

### ISSUE THREAD

**Issue by illcom94** [kidfearless/Foundry-TrueRNG#12]
Ran out of bits in the middle of a game today, and it was painfully obvious when it went back to the Foundry rolling. Would it be possible to put multiple keys in to use when you run out of bits, or at least notify the GM so they can enter a new key?

Thank you for this module!

**Comment by RyamosThomas** [comment]
A bit late in the response, but the right thing to do is to pay for random.org's api service. That will let you more dice.
