### ISSUE TITLE
An easy way to turn on and off the Random.org API

### ISSUE THREAD

**Issue by apoapostolov** [kidfearless/Foundry-TrueRNG#2]
A toolbar icon to pause the Random.ORG rolls and switch back to Python rand(). The purpose of this is to simplify turning Random.org calls while tinkering with your Foundry environment, turning on and off lots of mods and thus exhausting the free account resources (esp. for me with 8-12 sessions a week, I would prefer to keep it free and not exhaust it easily).

**Comment by RyamosThomas** [comment]
I can add a module setting to disable using the TrueRNG rolls. Though I don't know about a taskbar icon st this point.

**Comment by apoapostolov** [comment]
This is a bit clunky but very serviceable. Thanks in advance!

**Comment by RyamosThomas** [comment]
Added a quick toggle button for gm's to enable and disable the module. Will be available next release.
![image](https://user-images.githubusercontent.com/13614349/115100976-d86f0100-9efd-11eb-892c-c6330121c179.png)
