### ISSUE TITLE
A way for GM to fudge die rolls 

### ISSUE THREAD

**Issue by apoapostolov** [kidfearless/Foundry-TrueRNG#3]
This is going to be controversial, but this is something we need to keep our silly players alive.

A way to set a value or a logical requirement for the next roll. For example, the next d20 roll should roll ">15". 

I imagine it as a toolbar button that calls a dialog that contains what dice size to listen for (i.e. d20) and a logical requirement (, 15; >15, <12). The requirement affects only the next roll made - whether it is the GM or player's. If this can have a list of players and assign the fudge to a player only (to avoid someone rolling before that and stealing the fudge) even better. 

If combined with #2 this would be its own toolbar section with two icons - pause and fudge. 

P.S.: There's a similar small simple mod called Fudge, however it lacks the deep integration that True RNG provides and can only affects basic die rolls but not complex roll via mods like Better Roll for 5E, PF2's checks and strikes, etc. https://foundryvtt.com/packages/fudge

![image](https://user-images.githubusercontent.com/4083812/114437454-400c1000-9bcf-11eb-89eb-72bd30485d58.png)

**Comment by RyamosThomas** [comment]
This doesn't really fit in with the purpose of this module and probably won't be added.

**Comment by RyamosThomas** [comment]
I will add a some pre and post events that other modules can hook into in order for that kind of functionality to be compatible with TrueRNG.

**Comment by apoapostolov** [comment]
@kidfearless Thank you, that is more than enough. Would it be okay if I made an issue for the hook solution so it stays as reminder?

**Comment by RyamosThomas** [comment]
It's has been added under the projects tab. And can be followed there.
