### ISSUE TITLE
Debug Mode

### ISSUE THREAD

**Issue by apoapostolov** [kidfearless/Foundry-TrueRNG#5]
A way to make sure that each roll call uses TrueRNG, with a console message so we can confirm what rolls are using the mod and what are not for compatibility reasons.

**Comment by RyamosThomas** [comment]
This can be added as a debug mode module setting. There's debug messages in the source but we're commented out to keep the console clear.

**Comment by apoapostolov** [comment]
Thank you. This would be appreciated, but not a high priority.

**Comment by apoapostolov** [comment]
Thank you for this. Closing.
